name: Publish OpenFactory SDK Feature

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Publish feature to GHCR
        run: |
          devcontainer features publish \
            --namespace demo-smart-factory-concordia-university \
            --registry ghcr.io \
            ./.devcontainer/features/openfactory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
